import { Product, ProductStatus } from "./types";

export const mockProducts: Product[] = [
  {
    id: "product-1",
    title: "Домашние пирожки с капустой",
    description: "Свежие пирожки, тесто на кефире, начинка из тушёной капусты.",
    price: 350,
    category: "выпечка",
    images: ["https://picsum.photos/800/600?random=11"],
    region: "Москва",
    status: ProductStatus.APPROVED,
    seller_id: "seller-1",
    seller: {
      id: "seller-1",
      name: "Анна",
      avatar: "https://picsum.photos/200/200?random=101",
    },
    created_at: "2026-01-01",
  },
  {
    id: "product-2",
    title: "Чизкейк Нью-Йорк",
    description: "Классический чизкейк из сливочного сыра.",
    price: 1800,
    category: "десерты",
    images: ["https://picsum.photos/800/600?random=12"],
    region: "Москва",
    status: ProductStatus.APPROVED,
    seller_id: "seller-2",
    seller: {
      id: "seller-2",
      name: "Ирина",
      avatar: "https://picsum.photos/200/200?random=102",
    },
    created_at: "2026-01-02",
  },
  {
    id: "product-3",
    title: "Домашние закуски к столу",
    description: "Рулетики, канапе и овощные закуски.",
    price: 1200,
    category: "закуски",
    images: ["https://picsum.photos/800/600?random=13"],
    region: "Санкт-Петербург",
    status: ProductStatus.APPROVED,
    seller_id: "seller-3",
    seller: {
      id: "seller-3",
      name: "Марат",
      avatar: "https://picsum.photos/200/200?random=103",
    },
    created_at: "2026-01-03",
  },
  {
    id: "product-4",
    title: "Плов по-узбекски",
    description: "Ароматный плов с говядиной.",
    price: 700,
    category: "горячие блюда",
    images: ["https://picsum.photos/800/600?random=14"],
    region: "Казань",
    status: ProductStatus.APPROVED,
    seller_id: "seller-4",
    seller: {
      id: "seller-4",
      name: "Рустам",
      avatar: "https://picsum.photos/200/200?random=104",
    },
    created_at: "2026-01-04",
  },
  {
    id: "product-5",
    title: "Сырники со сметаной",
    description: "Нежные сырники из фермерского творога.",
    price: 400,
    category: "завтраки",
    images: ["https://picsum.photos/800/600?random=15"],
    region: "Москва",
    status: ProductStatus.APPROVED,
    seller_id: "seller-5",
    seller: {
      id: "seller-5",
      name: "Екатерина",
      avatar: "https://picsum.photos/200/200?random=105",
    },
    created_at: "2026-01-05",
  },
  {
    id: "product-6",
    title: "Домашний ягодный морс",
    description: "Натуральный морс из ягод, без сахара.",
    price: 250,
    category: "напитки",
    images: ["https://picsum.photos/800/600?random=16"],
    region: "Москва",
    status: ProductStatus.APPROVED,
    seller_id: "seller-6",
    seller: {
      id: "seller-6",
      name: "Ольга",
      avatar: "https://picsum.photos/200/200?random=106",
    },
    created_at: "2026-01-06",
  },
];



